### ISSUE TITLE
Error when installing on node version 12.16.2

### ISSUE THREAD

**Issue by vinhyenvodoi98** [Uniswap/v2-core#107]
## Problem

I got an error when running `yarn` command in node version 12.16.2
```sh
warning Error running install script for optional dependency: "/home/ubuntu/Desktop/test_for_friend/uniswap-v2-core/node_modules/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 

```
## Solution
I have to use node version 10.16.3 instead of version 12.16.2 . so it would be nice to have detailed version instructions in Readme.md

**Comment by business-helper** [comment]
I use Windows 10, could install the packages on node version 12.16.1, which was mentioned [here](https://github.com/eelcocramer/node-bluetooth-serial-port/issues/233#issuecomment-726412661).
